### ISSUE TITLE
Add BakeHouse

### ISSUE THREAD

**Issue by beccasjames** [paultag/dc#11]
Add BakeHouse to coffee.geojson

**Comment by paultag** [comment]
:+1:

**Comment by paultag** [comment]
> Sunday May, 22nd will be our last day of operation as a retail bakery.
> 
> Our wholesale business has taken off, so we are going to focus on this in order to allow for future growth.
> We will continue to operate out of our kitchen at 1407 T Street NW, and we have arranged for another local business to take over the storefront. (We’re not yet able to announce who’ll be moving in, but - for now - suffice it to say that we’re thrilled to be working with them, and we think they’ll be a great addition to the neighborhood!)
> 
> This decision is bittersweet in many ways (we’ll miss feeding and caffeinating our wonderful customers every morning!), but we’re excited to move forward on the wholesale track.
> We can’t thank you enough for your support and patronage over the last several years.
> 
> With ❤,
> BakeHouse
> P.S. Cravings for BakeHouse baked goods and sandwiches can still be indulged by visiting our wholesale outlets: Colony Club, Tynan Cofee and Tea, Qualia, both Pleasant Pops locations, the newly opened Philz stores in Adams Morgan and Navy Yard, as well as other places across DC and Northern Virginia.

**Comment by beccasjames** [comment]
At least someone will be replacing them shortly! Sad times, sad times.

^^ Maybe this gives us a reason to go to Tynan?
